#!/bin/bash
set -e

PATH="$PATH:/usr/bin/"
DISPLAY=1
DEPTH="24"
GEOMETRY="1360x768"
OPTIONS="-depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY} -localhost no"

case "$1" in
	start)
		/usr/bin/vncserver ${OPTIONS}
		;;
	stop)
		/usr/bin/vncserver -kill :${DISPLAY}
		;;
	restart)
		echo $0
		$0 stop
		$0 start
		;;
esac
exit 0

